/* DETAILS */
export const DETAILS_TOGGLE_EXPAND = 'DETAILS_TOGGLE_EXPAND';
export const DETAILS_SHARING_DIALOG_OPEN = 'DETAILS_SHARING_DIALOG_OPEN';
export const DETAILS_SHARING_DIALOG_CLOSE = 'DETAILS_SHARING_DIALOG_CLOSE';
export const DETAILS_DIALOG_OPEN = 'DETAILS_DIALOG_OPEN';
export const DETAILS_DIALOG_CLOSE = 'DETAILS_DIALOG_CLOSE';

/* INTERPRETATIONS */
export const INTERPRETATIONS_TOGGLE_EXPAND = 'INTERPRETATIONS_TOGGLE_EXPAND';
export const INTERPRETATIONS_SAVE = 'INTERPRETATIONS_SAVE';
export const INTERPRETATIONS_OPEN_WRITE_DIALOG = 'INTERPRETATIONS_OPEN_WRITE_DIALOG';
export const INTERPRETATIONS_CLOSE_WRITE_DIALOG = 'INTERPRETATIONS_CLOSE_WRITE_DIALOG';
export const INTERPRETATIONS_SET = 'INTERPRETATIONS_SET';
export const INTERPRETATIONS_SET_CURRENT = 'INTERPRETATIONS_SET_CURRENT';
export const INTERPRETATIONS_SAVE_LIKE_VALUE = 'INTERPRETATIONS_SAVE_LIKE_VALUE';
export const INTERPRETATIONS_DELETE = 'INTERPRETATIONS_DELETE';
export const INTERPRETATIONS_LOAD = 'INTERPRETATIONS_LOAD';
export const INTERPRETATIONS_SAVE_COMMENT = 'INTERPRETATIONS_SAVE_COMMENT';
export const INTERPRETATIONS_DELETE_COMMENT = 'INTERPRETATIONS_COMMENT_DELETE';
export const INTERPRETATIONS_ADD = 'INTERPRETATIONS_ADD';
